In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
import numpy as np
print(np.__version__)

1.25.2


In [3]:
import numpy as np

arr = np.array([[[1, 2, 3],[4, 5, 6]], [[1, 2, 3],[4, 5 , 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6], [1, 2, 3],[4, 5, 6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


___
### Array Indexing

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1] + arr[3])

1
6


### Access 2-D Arrays

In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row:', arr[0,1])

2nd element on 1st row: 2


In [19]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd row:', arr[1, 4])

5th element on 2nd row: 10


### Access 3-D Arrays

In [22]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

print(arr[0, 1, 2])

6


### Negative Indexing

In [26]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print('Last element from 2nd dim:', arr[1, -1])

Last element from 2nd dim: 10


___
### NumPy Array Slicing

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


### Step

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


### Slicing 2-D Arrays

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


___
## Numpy Data Yypes

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [13]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [20]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

### Converting Data Type on Existing Arrays


In [22]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [23]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64
