In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
import numpy as np
print(np.__version__)

1.25.2


In [3]:
import numpy as np

arr = np.array([[[1, 2, 3],[4, 5, 6]], [[1, 2, 3],[4, 5 , 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6], [1, 2, 3],[4, 5, 6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


___
### Array Indexing

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1] + arr[3])

1
6


### Access 2-D Arrays

In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row:', arr[0,1])

2nd element on 1st row: 2


In [19]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd row:', arr[1, 4])

5th element on 2nd row: 10


### Access 3-D Arrays

In [22]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

print(arr[0, 1, 2])

6


### Negative Indexing

In [26]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print('Last element from 2nd dim:', arr[1, -1])

Last element from 2nd dim: 10


___
### NumPy Array Slicing

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


### Step

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


### Slicing 2-D Arrays

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


___
## Numpy Data Yypes

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [13]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [20]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

### Converting Data Type on Existing Arrays


In [22]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [23]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [26]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


___
## NumPy Array Copy vs View

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
# Use Copy Methode
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
# Use View Methode
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


### Check if Array Owns its Data

In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) # Return none
print(y.base) # Return original object

None
[1 2 3 4 5]


___
## NumPy Array Shape


In [45]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array:', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


___
## NumPy Array Reshaping

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)
# cannot reshape array of size 8 into shape (3,3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 4)

print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the arrays

In [66]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6 7 8]


___
## NumPy Array Iterating

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [2]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [3]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [4]:
import numpy as np

arr = np.array([[[1, 2, 3],[4, 5, 6],[7, 8 ,9],[10, 11, 12]]])

for x in arr:
    print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
import numpy as np

arr = np.array([[[1, 2, 3],[4, 5, 6],[7, 8 ,9],[10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [15]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [16]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [20]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


___
## NumPy Joining Array

In [29]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

for x in arr:
    print(x)

[1 2 3 4 5 6]
1
2
3
4
5
6


In [35]:
import numpy as np

arr1 = np.array([[1, 2],[3, 4]])

arr2 = np.array([[5, 6],[7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [36]:
import numpy as np

arr1 = np.array([[1, 2],[3, 4]])

arr2 = np.array([[5, 6],[7, 8]])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [38]:
import numpy as np

arr1 = np.array([[1, 2],[3, 4]])

arr2 = np.array([[5, 6],[7, 8]])

arr = np.hstack((arr1, arr2))

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [45]:
import numpy as np

arr1 = np.array([[1, 2],[3, 4]])

arr2 = np.array([[5, 6],[7, 8]])

arr = np.vstack((arr1, arr2))

print(arr)

#for x in np.nditer(arr):
#    print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [43]:
import numpy as np

arr1 = np.array([[1, 2],[3, 4]])

arr2 = np.array([[5, 6],[7, 8]])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


___
## NumPy Splitting Array

In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

# My Idea:
#newarr2 = np.hstack((newarr[0], newarr[1]))
#print(newarr2)

[1 2]
[3 4]
[5 6]


In [65]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

# print(newarr[0])
# print(newarr[1])
# print(newarr[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [56]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [57]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [58]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


___
## NumPy Searching Arrays

In [71]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [72]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

x = np.where(arr %2 == 0)

print(x)

(array([1, 3, 5]),)


In [73]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr %2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [74]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [75]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side="right")

print(x)

2


In [76]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


___
## NumPy Sorting Arrays

In [79]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [80]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [81]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [82]:
import numpy as np

arr = np.array([[3, 2, 4],[5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
