SciPy Introduction

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **معرفی SciPy**

- SciPy یک کتابخانه محاسباتی علمی است که از NumPy در زیر آن استفاده می کند.
- SciPy مخفف Scientific Python است.
- این توابع کاربردی بیشتری برای بهینه سازی، آمار و پردازش سیگنال فراهم می کند.
- مانند NumPy، SciPy منبع باز است بنابراین می توانیم آزادانه از آن استفاده کنیم.
- SciPy توسط خالق NumPy Travis Olliphant ساخته شده است.

### چرا از SciPy استفاده می‌کنیم؟

اگر SciPy از NumPy در زیر استفاده می کند، چرا ما نمی توانیم فقط از NumPy استفاده کنیم؟
SciPy توابع بهینه سازی و اضافه کرده است که اغلب در NumPy و Data Science استفاده می شود.

### با کدام زبان SciPy نوشته شده است؟

SciPy عمدتاً در پایتون نوشته می شود، اما چند بخش به زبان C نوشته می شود.

### نصب SciPy

اگر پایتون و PIP را قبلاً روی یک سیستم نصب کرده اید، نصب SciPy بسیار آسان است.
با استفاده از این دستور آن را نصب کنید:

</section>

> C:\Users\Your Name>pip install scipy

In [5]:
from scipy import constants

print(constants.liter)

0.001


<section style="direction: rtl; text-align: justify; margin: 30px;">

ثابت‌ها (constants): SciPy مجموعه ای از ثابت های ریاضی را ارائه می دهد که یکی از آنها liter است که 1 لیتر را به عنوان متر مکعب برمی گرداند.


</section>

In [6]:
# Checking SciPy Version

import scipy

print(scipy.__version__)

1.11.2


___
SciPy Constants

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **ثابت‌ها**

از آنجایی که SciPy بیشتر بر پیاده سازی های علمی متمرکز است، بسیاری از ثابت های علمی داخلی را ارائه می دهد.
هنگامی که با Data Science کار می کنید، این ثابت ها می توانند مفید باشند.

PI (عدد پی) نمونه ای از ثابت علمی است .


</section>

In [1]:
from scipy import constants

print(constants.pi)

3.141592653589793


Constant Units

<section style="direction: rtl; text-align: justify; margin: 30px;">

### **واحدهای ثابت**

با استفاده از تابع dir () می توان لیستی از تمام واحدها را در ماژول ثابت ها مشاهده کرد.



</section>

In [2]:
from scipy import constants

print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', '

Unit Categories

<section style="direction: rtl; text-align: justify; margin: 30px;">

### **دسته‌بندی‌های واحد**

واحدها در این دسته بندی ها قرار می گیرند:

</section>

- Metric
- Binary
- Mass
- Angle
- Time
- Length
- Pressure
- Volume
- Speed
- Temperature
- Energy
- Power
- Force

<section style="direction: rtl; text-align: justify; margin: 30px;">

### **پیشوندهای متریک**

</section>

In [5]:
# Return the specified unit in meter (e.g. centi returns 0.01)

from scipy import constants

print(constants.yotta)    #1e+24
print(constants.zetta)    #1e+21
print(constants.exa)      #1e+18
print(constants.peta)     #1000000000000000.0
print(constants.tera)     #1000000000000.0
print(constants.giga)     #1000000000.0
print(constants.mega)     #1000000.0
print(constants.kilo)     #1000.0
print(constants.hecto)    #100.0
print(constants.deka)     #10.0
print(constants.deci)     #0.1
print(constants.centi)    #0.01
print(constants.milli)    #0.001
print(constants.micro)    #1e-06
print(constants.nano)     #1e-09
print(constants.pico)     #1e-12
print(constants.femto)    #1e-15
print(constants.atto)     #1e-18
print(constants.zepto)    #1e-21


1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **پیشوندهای باینری**

</section>

In [7]:
# Return the specified unit in bytes (e.g. kibi returns 1024)

print(constants.kibi)    #1024
print(constants.mebi)    #1048576
print(constants.gibi)    #1073741824
print(constants.tebi)    #1099511627776
print(constants.pebi)    #1125899906842624
print(constants.exbi)    #1152921504606846976
print(constants.zebi)    #1180591620717411303424
print(constants.yobi)    #1208925819614629174706176

1024
1048576
1073741824
1099511627776
1125899906842624
1152921504606846976
1180591620717411303424
1208925819614629174706176


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **جِرم**

</section>

In [8]:
# Return the specified unit in kg (e.g. gram returns 0.001)

print(constants.gram)        #0.001
print(constants.metric_ton)  #1000.0
print(constants.grain)       #6.479891e-05
print(constants.lb)          #0.45359236999999997
print(constants.pound)       #0.45359236999999997
print(constants.oz)          #0.028349523124999998
print(constants.ounce)       #0.028349523124999998
print(constants.stone)       #6.3502931799999995
print(constants.long_ton)    #1016.0469088
print(constants.short_ton)   #907.1847399999999
print(constants.troy_ounce)  #0.031103476799999998
print(constants.troy_pound)  #0.37324172159999996
print(constants.carat)       #0.0002
print(constants.atomic_mass) #1.66053904e-27
print(constants.m_u)         #1.66053904e-27
print(constants.u)           #1.66053904e-27

0.001
1000.0
6.479891e-05
0.45359236999999997
0.45359236999999997
0.028349523124999998
0.028349523124999998
6.3502931799999995
1016.0469088
907.1847399999999
0.031103476799999998
0.37324172159999996
0.0002
1.6605390666e-27
1.6605390666e-27
1.6605390666e-27


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **زاویه**

</section>

In [9]:
# Return the specified unit in radians (e.g. degree returns 0.017453292519943295)

from scipy import constants

print(constants.degree)     #0.017453292519943295
print(constants.arcmin)     #0.0002908882086657216
print(constants.arcminute)  #0.0002908882086657216
print(constants.arcsec)     #4.84813681109536e-06
print(constants.arcsecond)  #4.84813681109536e-06

0.017453292519943295
0.0002908882086657216
0.0002908882086657216
4.84813681109536e-06
4.84813681109536e-06


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **زمان**

</section>

In [10]:
# Return the specified unit in seconds (e.g. hour returns 3600.0)

from scipy import constants

print(constants.minute)      #60.0
print(constants.hour)        #3600.0
print(constants.day)         #86400.0
print(constants.week)        #604800.0
print(constants.year)        #31536000.0
print(constants.Julian_year) #31557600.0

60.0
3600.0
86400.0
604800.0
31536000.0
31557600.0


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **طول**

</section>

In [12]:
# Return the specified unit in meters (e.g. nautical_mile returns 1852.0)

print(constants.inch)              #0.0254
print(constants.foot)              #0.30479999999999996
print(constants.yard)              #0.9143999999999999
print(constants.mile)              #1609.3439999999998
print(constants.mil)               #2.5399999999999997e-05
print(constants.pt)                #0.00035277777777777776
print(constants.point)             #0.00035277777777777776
print(constants.survey_foot)       #0.3048006096012192
print(constants.survey_mile)       #1609.3472186944373
print(constants.nautical_mile)     #1852.0
print(constants.fermi)             #1e-15
print(constants.angstrom)          #1e-10
print(constants.micron)            #1e-06
print(constants.au)                #149597870691.0
print(constants.astronomical_unit) #149597870691.0
print(constants.light_year)        #9460730472580800.0
print(constants.parsec)            #3.0856775813057292e+16

0.0254
0.30479999999999996
0.9143999999999999
1609.3439999999998
2.5399999999999997e-05
0.00035277777777777776
0.00035277777777777776
0.3048006096012192
1609.3472186944373
1852.0
1e-15
1e-10
1e-06
149597870700.0
149597870700.0
9460730472580800.0
3.085677581491367e+16


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **فشار**

</section>

In [13]:
# Return the specified unit in pascals (e.g. psi returns 6894.757293168361)

from scipy import constants

print(constants.atm)         #101325.0
print(constants.atmosphere)  #101325.0
print(constants.bar)         #100000.0
print(constants.torr)        #133.32236842105263
print(constants.mmHg)        #133.32236842105263
print(constants.psi)         #6894.757293168361

101325.0
101325.0
100000.0
133.32236842105263
133.32236842105263
6894.757293168361


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **مساحت**

</section>

In [14]:
# Return the specified unit in square meters(e.g. hectare returns 10000.0)

from scipy import constants

print(constants.hectare) #10000.0
print(constants.acre)    #4046.8564223999992

10000.0
4046.8564223999992


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **افزایش حجم (Volume)**

</section>

In [15]:
# Return the specified unit in cubic meters (e.g. liter returns 0.001)

print(constants.liter)            #0.001
print(constants.litre)            #0.001
print(constants.gallon)           #0.0037854117839999997
print(constants.gallon_US)        #0.0037854117839999997
print(constants.gallon_imp)       #0.00454609
print(constants.fluid_ounce)      #2.9573529562499998e-05
print(constants.fluid_ounce_US)   #2.9573529562499998e-05
print(constants.fluid_ounce_imp)  #2.84130625e-05
print(constants.barrel)           #0.15898729492799998
print(constants.bbl)              #0.15898729492799998

0.001
0.001
0.0037854117839999997
0.0037854117839999997
0.00454609
2.9573529562499998e-05
2.9573529562499998e-05
2.84130625e-05
0.15898729492799998
0.15898729492799998


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **سرعت**

</section>

In [16]:
# Return the specified unit in meters per second (e.g. speed_of_sound returns 340.5)

from scipy import constants

print(constants.kmh)            #0.2777777777777778
print(constants.mph)            #0.44703999999999994
print(constants.mach)           #340.5
print(constants.speed_of_sound) #340.5
print(constants.knot)           #0.5144444444444445

0.2777777777777778
0.44703999999999994
340.5
340.5
0.5144444444444445


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **درجه حرارت**

</section>

In [17]:
# Return the specified unit in Kelvin (e.g. zero_Celsius returns 273.15)

from scipy import constants

print(constants.zero_Celsius)      #273.15
print(constants.degree_Fahrenheit) #0.5555555555555556

273.15
0.5555555555555556


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **انرژی**

</section>

In [18]:
# Return the specified unit in joules (e.g. calorie returns 4.184)

from scipy import constants

print(constants.eV)            #1.6021766208e-19
print(constants.electron_volt) #1.6021766208e-19
print(constants.calorie)       #4.184
print(constants.calorie_th)    #4.184
print(constants.calorie_IT)    #4.1868
print(constants.erg)           #1e-07
print(constants.Btu)           #1055.05585262
print(constants.Btu_IT)        #1055.05585262
print(constants.Btu_th)        #1054.3502644888888
print(constants.ton_TNT)       #4184000000.0

1.602176634e-19
1.602176634e-19
4.184
4.184
4.1868
1e-07
1055.05585262
1055.05585262
1054.3502644888888
4184000000.0


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **برق**

</section>

In [19]:
# Return the specified unit in watts (e.g. horsepower returns 745.6998715822701)

from scipy import constants

print(constants.hp)         #745.6998715822701
print(constants.horsepower) #745.6998715822701

745.6998715822701
745.6998715822701


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **کیلوگرم - نیرو**

</section>

In [20]:
# Return the specified unit in newton (e.g. kilogram_force returns 9.80665)

from scipy import constants

print(constants.dyn)             #1e-05
print(constants.dyne)            #1e-05
print(constants.lbf)             #4.4482216152605
print(constants.pound_force)     #4.4482216152605
print(constants.kgf)             #9.80665
print(constants.kilogram_force)  #9.80665

1e-05
1e-05
4.4482216152605
4.4482216152605
9.80665
9.80665


___
SciPy Optimizers

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **بهینه‌سازهای SciPy**

بهینه سازها مجموعه ای از روش های تعریف شده در SciPy هستند که یا مقدار کمینه یک تابع را پیدا می کنند یا ریشه یک معادله را پیدا می کنند. برای بهینه سازی توابع، اساساً تمام الگوریتم های یادگیری ماشین چیز دیگری نیستند جز یک معادله پیچیده که با کمک داده های داده شده باید کمینه شود. برای پیدا کردن ریشه یک معادله، مانند x + cos (x)، می توان از تابع optimize.root SciPy استفاده کرد. این تابع دو آرگومان ضروری را دریافت می کند: fun - یک تابع که نشان دهنده یک معادله است. x0 - حدس اولیه برای ریشه. تابع یک شئ با اطلاعات مربوط به راه حل برمی گرداند. راه حل واقعی زیر ویژگی x شئ بازگشت داده شده است:


</section>

In [3]:
from scipy.optimize import root
from math import cos

def eqn(x):
    return x + cos(x)

myroot = root(eqn, 0)

print(myroot.x)

[-0.73908513]


/tmp/ipykernel_544/3334356547.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return x + cos(x)


In [4]:
print(myroot)

 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00]
       x: [-7.391e-01]
    nfev: 9
    fjac: [[-1.000e+00]]
       r: [-1.674e+00]
     qtf: [-2.668e-13]


<section style="direction: rtl; text-align: justify; margin: 30px;">

برای بهینه سازی تابع، می توان از تابع scipy.optimize.minimize () استفاده کرد. تابع minimize () آرگومان های زیر را دریافت می کند:
-	fun - یک تابع نشان دهنده یک معادله.
-	x0 - حدس اوليه برای ريشه.
-	method - نام روش برای استفاده.
-	مقادیر قانوني:
    -	 ‘CG’ 
    -    ‘BFGS’
    -	 ‘Newton-CG’
    -	 ‘L-BFGS-B’
    -	 ‘TNC’
    -	 ‘COBYLA’
    -	 ‘SLSQP’ 
-	callback - تابعي كه پس از هر بار بهينه سازي فراخواني مي شود.
-	options - يك واژكاري كليدي كه پارامتر هاي اضافي را تعريف مي كند: 

</section>

{

     "disp": boolean - print detailed description

     "gtol": number - the tolerance of the error

}

In [5]:
from scipy.optimize import minimize

def eqn(x):
    return x**2 + x + 2

mymin = minimize(eqn, 0, method="BFGS")

print(mymin)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 1.75
        x: [-5.000e-01]
      nit: 2
      jac: [ 0.000e+00]
 hess_inv: [[ 5.000e-01]]
     nfev: 8
     njev: 4


___
SciPy Sparse Data

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **داده‌های پراکنده**

داده‌های پراکنده داده‌هایی هستند که عمدتاً دارای عناصر استفاده نشده هستند (عناصری که هیچ اطلاعاتی ندارند).

می تواند آرایه ای مانند این باشد:
[1, 0, 2, 0, 0, 3, 0, 0, 0, 0, 0, 0]

داده‌های پراکنده: مجموعه داده ای است که در آن بیشتر مقادیر آیتم ها صفر است.

آرایه متراکم: مخالف آرایه پراکنده است: بیشتر مقادیر صفر نیستند.

</section>



In [13]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])

print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


<section style="direction: rtl; text-align: justify; margin: 30px;">

### **روش‌های داده‌های پراکنده**

مشاهده داده های ذخیره شده (نه موارد صفر) با ویژگی داده:

</section>

In [15]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

print(csr_matrix(arr).data)

[1 1 2]


<section style="direction: rtl; text-align: justify; margin: 30px;">

شمارش غیر صفرها با متد count_nonzero():

</section>

In [17]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

print(csr_matrix(arr).count_nonzero())

3


<section style="direction: rtl; text-align: justify; margin: 30px;">

حذف ورودی‌های صفر از ماتریس با متد elimin_zeros():

</section>

In [24]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

mat = csr_matrix(arr)
mat.eliminate_zeros()

print(mat)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


<section style="direction: rtl; text-align: justify; margin: 30px;">

حذف ورودی های تکراری با متد ()sum_duplicates:

</section>

In [19]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

mat = csr_matrix(arr)
mat.sum_duplicates()

print(mat)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


<section style="direction: rtl; text-align: justify; margin: 30px;">

تبدیل از csr به csc با متد tocsc() :

</section>

In [25]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

newarr = csr_matrix(arr).tocsc()

print(newarr)

  (2, 0)	1
  (1, 2)	1
  (2, 2)	2


___
SciPy Graphs

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **نمودارها**

نمودارها یک ساختار داده ضروری هستند.

SciPy ماژول scipy.sparse.csgraph را برای کار با چنین ساختارهای داده ای در اختیار ما قرار می دهد.

### **ماتریس مجاورت**

ماتریس مجاورت یک ماتریس nxn است که n تعداد عناصر یک گراف است.

و مقادیر نشان دهنده ارتباط بین عناصر است.

![Graph](https://www.w3schools.com/python/scipy_graph.png)

برای نموداری مانند این، با عناصر A، B و C، اتصالات عبارتند از:
- A و B با وزن 1 مرتبط هستند.
- A و C با وزن 2 مرتبط هستند.
- C & B متصل نیست.

### **اجزای مجاورت**

تمام اجزای متصل را با متد ()connected_components پیدا کنید.

</section>



In [2]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)
print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


Dijkstra

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **Dijkstra**

از روش dijkstra برای یافتن کوتاه ترین مسیر در یک نمودار از یک عنصر به عنصر دیگر استفاده کنید.

آرگومان‌های زیر را می گیرد:

- return_predecessors: یک مقدار بولین میگیرد، درست برای بازگشت کل مسیر پیمایش، در غیر این صورت غلط
- indices: شاخص عنصر برای برگرداندن تمام مسیرها فقط از آن عنصر.
- limit: حداکثر وزن مسیر.

</section>



In [14]:
# Find the shortest path from element 1 to 2:

import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)

print(dijkstra(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


Floyd Warshall

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **Floyd Warshall**

از متد floyd_warshall() برای یافتن کوتاه ترین مسیر بین تمام جفت عناصر استفاده کنید.

</section>



In [16]:
# Find the shortest path between all pairs of elements:

import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)
print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


Bellman Ford

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **Bellman Ford**

متد bellman_ford() همچنین می‌تواند کوتاه‌ترین مسیر را بین تمام جفت‌های عنصر پیدا کند، اما این روش می‌تواند وزن‌های منفی را نیز مدیریت کند.

</section>



In [17]:
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)

print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


Depth First Order

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **مرتبه اول عمق**

متد ()depth_first_order اولین پیمایش عمق را از یک گره برمی‌گرداند.

این تابع آرگومان های زیر را می گیرد:
- نمودار
- عنصر شروع برای عبور از نمودار.

</section>



In [18]:
# Traverse the graph depth first for given adjacency matrix:

import numpy as np
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(depth_first_order(newarr, 1))

(array([1, 0, 3, 2], dtype=int32), array([    1, -9999,     1,     0], dtype=int32))


Breadth First Order

<section style="direction: rtl; text-align: justify; margin: 30px;">

## **عرض اول**

متد width_first_order() اولین پیمایش وسعت را از یک گره برمی گرداند.

این تابع آرگومان های زیر را می گیرد:
- نمودار
- عنصر شروع برای عبور از نمودار.

</section>



In [19]:
import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(breadth_first_order(newarr, 1))

(array([1, 0, 2, 3], dtype=int32), array([    1, -9999,     1,     1], dtype=int32))
